name: SkASWM
description: Skript addon for managing SlimeWorldManager
version: '${version}'
main: me.danielmillar.skaswm.SkASWM
api-version: '1.20'
authors:
  - Daniel Millar
load: POSTWORLD
depend:
  - Skript
  - SlimeWorldManager

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0
  - de.exlll:configlib-yaml:4.5.0